---
name: DRKKoth
author: DarkkzMC
description: A Koth plugin By DarkkzMC
version: 0.0.1
main: DarkkzMC\Koth\KothMain
api:
- 3.0.0
- 3.0.0-ALPHA5
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
- 3.0.0-ALPHA16
- 3.0.0-ALPHA17
- 3.0.0-ALPHA18
- 3.0.0-ALPHA19
- 3.0.0-ALPHA20
- 3.8.2
...
